# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChindrenCare' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChindrenCare
  platform :ios, '9.0'
  pod 'Firebase/Core', '~> 5.11.0'
  pod 'Firebase/Auth', '~> 5.11.0'
  pod 'Firebase/Messaging', '~> 5.11.0'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

  pod 'RNViewShot', :path => '../node_modules/react-native-view-shot'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'ChindrenCareTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ChindrenCare-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ChindrenCare-tvOS

  target 'ChindrenCare-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
